#### ----------------------------------------####
###
## MANDATORY PARAMETERS
###
#### ----------------------------------------####

#Input CSV with reads
metadata: '/home/users/s/stubbe/CR_meta.csv'

#Output directory
outdir: '/home/users/s/stubbe/CR_2_output/'

#Genome file
igenomes_base: '/home/users/s/stubbe/resources/igenomes'
genome: 'WBcel235' 
spike_genome: 'EB1'

#Normalisation
normalisation_to_spikein: true
normalisation_mode: 'CPM'

#Make genomic tiles
split: true
splitwindows: '/home/users/s/stubbe/resources/Genomic_windows/5kb_WBCel235.bed'
